[2021-12-03 23:56:58,495] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_vascodagama 2021-11-28T09:00:00+00:00 [queued]>
[2021-12-03 23:56:58,503] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_vascodagama 2021-11-28T09:00:00+00:00 [queued]>
[2021-12-03 23:56:58,503] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-12-03 23:56:58,503] {taskinstance.py:881} INFO - Starting attempt 7 of 7
[2021-12-03 23:56:58,503] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-12-03 23:56:58,509] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_vascodagama> on 2021-11-28T09:00:00+00:00
[2021-12-03 23:56:58,511] {standard_task_runner.py:54} INFO - Started process 9806 to run task
[2021-12-03 23:56:58,553] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_vascodagama', '2021-11-28T09:00:00+00:00', '--job_id', '112', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmp2r7z_15w']
[2021-12-03 23:56:58,554] {standard_task_runner.py:78} INFO - Job 112: Subtask twitter_vascodagama
[2021-12-03 23:56:58,570] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_vascodagama 2021-11-28T09:00:00+00:00 [running]> on host kauai-VirtualBox
[2021-12-03 23:56:58,603] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2021-12-03 23:56:58,605] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=VascodaGama&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-11-28T09:00:00.00Z&end_time=2021-11-29T09:00:00.00Z
[2021-12-03 23:56:58,858] {logging_mixin.py:112} WARNING - /home/kauai/datapipeline/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-12-03 23:56:59,130] {http_hook.py:150} ERROR - HTTP error: Too Many Requests
[2021-12-03 23:56:59,130] {http_hook.py:151} ERROR - {"title":"Too Many Requests","detail":"Too Many Requests","type":"about:blank","status":429}
[2021-12-03 23:56:59,135] {taskinstance.py:1150} ERROR - 429:Too Many Requests
Traceback (most recent call last):
  File "/home/kauai/datapipeline/venv/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 148, in check_response
    response.raise_for_status()
  File "/home/kauai/datapipeline/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.twitter.com/2/tweets/search/recent?query=VascodaGama&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-11-28T09:00:00.00Z&end_time=2021-11-29T09:00:00.00Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kauai/datapipeline/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/kauai/airflow/plugins/operators/twitter_operator.py", line 49, in execute
    for pg in hook.run():
  File "/home/kauai/airflow/plugins/hooks/twitter_hook.py", line 56, in run
    yield from self.paginate(url, session)
  File "/home/kauai/airflow/plugins/hooks/twitter_hook.py", line 45, in paginate
    data = self.connect_to_endpoint(full_url, session)
  File "/home/kauai/airflow/plugins/hooks/twitter_hook.py", line 37, in connect_to_endpoint
    return self.run_and_check(session, prep, {}).json()
  File "/home/kauai/datapipeline/venv/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 181, in run_and_check
    self.check_response(response)
  File "/home/kauai/datapipeline/venv/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 152, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 429:Too Many Requests
[2021-12-03 23:56:59,136] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_vascodagama, execution_date=20211128T090000, start_date=20211204T025658, end_date=20211204T025659
[2021-12-03 23:57:03,486] {local_task_job.py:102} INFO - Task exited with return code 1
