[2021-11-29 23:53:32,925] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-11-28T09:00:00+00:00 [queued]>
[2021-11-29 23:53:32,932] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-11-28T09:00:00+00:00 [queued]>
[2021-11-29 23:53:32,933] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 23:53:32,933] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-11-29 23:53:32,933] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 23:53:32,940] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2021-11-28T09:00:00+00:00
[2021-11-29 23:53:32,942] {standard_task_runner.py:54} INFO - Started process 4865 to run task
[2021-11-29 23:53:32,990] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2021-11-28T09:00:00+00:00', '--job_id', '29', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmpaiktqlw2']
[2021-11-29 23:53:32,991] {standard_task_runner.py:78} INFO - Job 29: Subtask twitter_aluraonline
[2021-11-29 23:53:33,010] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2021-11-28T09:00:00+00:00 [running]> on host kauai-VirtualBox
[2021-11-29 23:53:33,043] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2021-11-29 23:53:33,044] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-11-28T09:00:00.00Z&end_time=2021-11-29T09:00:00.00Z
[2021-11-29 23:53:33,298] {logging_mixin.py:112} WARNING - /home/kauai/datapipeline/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-11-29 23:53:33,674] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-11-28T09:00:00.00Z&end_time=2021-11-29T09:00:00.00Z&next_token=b26v89c19zqg8o3fpdy7ny0rikah021207xx7mnx7kpkt
[2021-11-29 23:53:33,674] {logging_mixin.py:112} WARNING - /home/kauai/datapipeline/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-11-29 23:53:34,081] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-11-28T09:00:00.00Z&end_time=2021-11-29T09:00:00.00Z&next_token=b26v89c19zqg8o3fpdy79bly7qyu4oj04flkxshlwri4d
[2021-11-29 23:53:34,082] {logging_mixin.py:112} WARNING - /home/kauai/datapipeline/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-11-29 23:53:34,444] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20211128T090000, start_date=20211130T025332, end_date=20211130T025334
[2021-11-29 23:53:37,935] {local_task_job.py:102} INFO - Task exited with return code 0
